compressionLevel: 0

enableImmutableInstalls: false

nmHoistingLimits: none

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
